version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
  build:
    working_directory: /docker-app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install dependencies"
          command: |
            apk add --no-cache \
              py-pip 
            pip install  \
              awscli
      - run:
          name: "Build docker image"
          command: |
            docker build -t docker-app ./docker-app
      - deploy:
          name: "Push to AWS ECR"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
