version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.0
  aws-ecs: circleci/aws-ecs@3.0.0
commands:
  say_hello:
    description: "Say hello CircleCi"
    steps:
    - run: echo "Hello from commands"
workflows:
  build-and-deploy:
    jobs:
      - say_hello
      - aws-ecr/build-and-push-image:
          repo: $REPOSITORY_NAME
          tag: "latest"
          dockerfile: docker-app/Dockerfile
          path: .
      - aws-ecs/deploy-service-update:
          cluster: $ECS_CLUSTER_NAME
          container-image-name-updates: "container=${CONTAINER_NAME},image-and-tag=${IMAGE_AND_TAG_NAME}"
          family: $ECS_TASK_FAMILY
          service-name: $ECS_SERVICE
          requires:
            - aws-ecr/build-and-push-image
