version: 2.1
jobs:
  build:
    working_directory: /docker-app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: "Install dependencies"
          command: |
            apk add --no-cache py-pip \
            pip install awscli
