version: 2.1
jobs:
  build:
    working_directory: /docker-app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install dependencies"
          command: |
            apk add --no-cache \
              py-pip 
            pip install  \
              awscli
      - run:
          name: "Build docker image"
          command: |
            docker build -t docker-app ./docker-app
      - deploy:
          name: "Push to AWS ECR"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi
