version: 2.1
jobs:
  build:
    working_directory: /docker-app
    docker: 
    - image: docker:latest
    steps:
      - run:
          name: "Install dependencies"
          command: |
            pip install awscli

