version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.0
  aws-ecs: circleci/aws-ecs@3.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: circleci-learning
          tag: "latest"
          dockerfile: docker-app/Dockerfile
          path: .
      - aws-ecs/deploy-service-update:
          cluster: 'CircleCI-cluster'
          container-image-name-updates: 'container=circleci,tag=latest'
          family: 'circleci-task'
          requires:
            - aws-ecr/build-and-push-image